---
- name: Run commands on all Aristas
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: configure hostname
      eos_config:
        authorize: yes
        auth_pass: "TT3.0rc1"
        username: "gag"
        password: "GAGletmein123@"
        lines: 
          - hostname {{ tags.name }}
          - logging host {{ syslog_servers[0].ip }}
          - snmp-server host {{ snmp_servers[0].ip }} version 2c telconms1
          - snmp-server enable traps
          - snmp-server enable traps entity
